### ISSUE TITLE
Wrong agency tag on TROPOMI NO2

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash-catalog#184]
Indicator metadata is wrongly shown:
https://www.eodashboard.org/explore?indicator=N1_NO2&x=0&y=-1224599.44035&z=2.35425
<img width="1435" alt="Screenshot 2024-08-08 at 13 08 21" src="https://github.com/user-attachments/assets/b7d8adb6-81c7-4cff-80c5-e629a6cbc263">

even if the content in the yaml is correct 
https://github.com/eurodatacube/eodash-catalog/blob/main/collections/N1_NO2.yaml 

I think it references the wrong yaml: N1_NO2_trilateral.yaml

**Comment by aapopescu** [comment]
@dmoglioni , @FedericoRondoni , can you please help to verify if this happens in more datasets?

**Comment by lubojr** [comment]
https://github.com/eurodatacube/eodash-catalog/blob/main/collections/N1_NO2_trilateral.yaml This is the YAML used for trilateral due to usage of a different description text in the pre-STAC dashboard. If it can be the same for both occurence in RACE and eodashboard then @FedericoRondoni please delete the N1_NO2_trilateral.yaml and change the file reference to N1_NO2 in https://github.com/eurodatacube/eodash-catalog/blob/main/catalogs/trilateral.yaml#L8

**Comment by santilland** [comment]
Confirmed that dedicated trilateral version is no longer needed, let's go ahead with removing it
